version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tonano
      POSTGRES_USER: tonano
      POSTGRES_PASSWORD: tonano
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./my_custom_postgres.conf:/var/lib/postgresql/data/postgresql.conf
    shm_size: 1g

  indexer0:
    depends_on:
      - postgres
    environment:
      PROD: 1
    build:
      context: ./indexer
    command: sh -c "python3.9 manage.py migrate && python3.9 manage.py start_index"
    restart: always

  ton20index:
    depends_on:
      - postgres
    environment:
      PROD: 1
    build:
      context: ./indexer
    command: sh -c "python3.9 manage.py start_ton20"
    restart: always

  api:
    depends_on:
      - postgres
    environment:
      PROD: 1
    build:
      context: ./indexer
    command: sh -c "python3.9 manage.py collectstatic && gunicorn tonano.wsgi:application --bind 0.0.0.0:8090"
    ports:
      - 8090:8090
    restart: always

  notebooks:
    depends_on:
      - postgres
    environment:
      PROD: 1
    ports:
      - 8989:8989
    build:
      context: ./indexer
    command: sh -c "jupyter notebook --allow-root --port 8989 --ip 0.0.0.0"
    restart: always
    volumes:
      - notebook_data:/code/notebooks



volumes:
  notebook_data:
  postgres_data: