# Generated by Django 5.0.2 on 2024-03-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_utime', models.DateTimeField()),
                ('workchain', models.IntegerField()),
                ('shard', models.BigIntegerField()),
                ('seqno', models.BigIntegerField()),
                ('root_hash', models.CharField(max_length=200, null=True)),
                ('file_hash', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_ref_seqno', models.BigIntegerField()),
                ('gen_utime', models.DateTimeField()),
                ('workchain', models.IntegerField()),
                ('shard', models.BigIntegerField()),
                ('seqno', models.BigIntegerField()),
                ('root_hash', models.CharField(max_length=200, null=True)),
                ('file_hash', models.CharField(max_length=200, null=True)),
                ('lt', models.BigIntegerField()),
                ('now', models.DateTimeField()),
                ('account', models.CharField(max_length=200)),
                ('transaction_hash', models.CharField(max_length=200, unique=True)),
                ('transaction_boc', models.TextField()),
            ],
        ),
    ]
