# Generated by Django 5.0.2 on 2024-03-02 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gen_utime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='now',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
