# Generated by Django 5.0.2 on 2024-03-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0002_alter_transaction_gen_utime_alter_transaction_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='lt',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mc_ref_seqno',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seqno',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shard',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
    ]
