# Generated by Django 5.0.2 on 2024-03-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0003_alter_transaction_lt_alter_transaction_mc_ref_seqno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestindex',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='latestindex',
            name='gen_utime',
        ),
        migrations.RemoveField(
            model_name='latestindex',
            name='root_hash',
        ),
        migrations.RemoveField(
            model_name='latestindex',
            name='shard',
        ),
        migrations.RemoveField(
            model_name='latestindex',
            name='workchain',
        ),
    ]
