# Generated by Django 5.0.2 on 2024-03-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0004_remove_latestindex_file_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='in_msg_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='in_msg_created_at',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='in_msg_created_lt',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='in_msg_hash',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='in_msg_src_addr_address_hex',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='in_msg_src_addr_workchain_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='in_msg_value_grams',
            field=models.DecimalField(decimal_places=0, max_digits=78, null=True),
        ),
    ]
