# Generated by Django 5.0.2 on 2024-04-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0006_transaction_indexer_tra_gen_uti_1a5f35_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['in_msg_created_lt'], name='indexer_tra_in_msg__22f753_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['gen_utime', 'lt', 'in_msg_created_lt'], name='indexer_tra_gen_uti_ee999d_idx'),
        ),
    ]
