# Generated by Django 5.0.2 on 2024-04-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0007_transaction_indexer_tra_in_msg__22f753_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCache',
            fields=[
                ('address', models.CharField(max_length=67, primary_key=True, serialize=False, unique=True)),
                ('is_contract_wallet', models.BooleanField(default=False)),
                ('account_blacklist', models.BooleanField(default=False)),
                ('smc_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['in_msg_src_addr_workchain_id', 'in_msg_src_addr_address_hex'], name='indexer_tra_in_msg__cf05d8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['root_hash'], name='indexer_tra_root_ha_dd7858_idx'),
        ),
    ]
