# Generated by Django 5.0.2 on 2024-04-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0008_accountcache_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountcache',
            index=models.Index(fields=['address'], name='indexer_acc_address_3919cd_idx'),
        ),
        migrations.AddIndex(
            model_name='accountcache',
            index=models.Index(fields=['smc_hash'], name='indexer_acc_smc_has_7b3f61_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_hash'], name='indexer_tra_transac_469904_idx'),
        ),
    ]
