# Generated by Django 5.0.2 on 2024-04-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0009_accountcache_indexer_acc_address_3919cd_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['mc_ref_seqno'], name='indexer_tra_mc_ref__0ece2b_idx'),
        ),
    ]
