# Generated by Django 5.0.2 on 2024-04-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0011_transaction_fail_reason_transaction_success'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['in_msg_created_lt', 'in_msg_hash'], name='indexer_tra_in_msg__a27a3f_idx'),
        ),
    ]
