# Generated by Django 5.0.2 on 2024-05-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0012_transaction_indexer_tra_in_msg__a27a3f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('transaction_hash', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('success', models.BooleanField(default=False)),
                ('fail_reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ton20StateSerialized',
            fields=[
                ('state_hash', models.CharField(max_length=67, primary_key=True, serialize=False, unique=True)),
                ('in_msg_created_lt', models.IntegerField()),
                ('transaction_hash', models.CharField(max_length=67, unique=True)),
                ('state_boc', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['in_msg_created_lt'], name='indexer_ton_in_msg__cd7af7_idx'), models.Index(fields=['transaction_hash'], name='indexer_ton_transac_fc3e97_idx')],
            },
        ),
    ]
