# Generated by Django 5.0.2 on 2024-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0013_transactionstatus_ton20stateserialized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ton20stateserialized',
            name='in_msg_created_lt',
            field=models.BigIntegerField(),
        ),
    ]
