# Generated by Django 5.0.2 on 2024-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0014_alter_ton20stateserialized_in_msg_created_lt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fail_reason',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='success',
        ),
        migrations.CreateModel(
            name='Ton20Tick',
            fields=[
                ('tick', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('max', models.DecimalField(decimal_places=0, max_digits=78, null=True)),
                ('lim', models.DecimalField(decimal_places=0, max_digits=78, null=True)),
                ('rest', models.DecimalField(decimal_places=0, max_digits=78, null=True)),
                ('deploy_by', models.CharField(max_length=67)),
                ('txhash', models.CharField(max_length=67)),
            ],
            options={
                'indexes': [models.Index(fields=['deploy_by'], name='indexer_ton_deploy__52121a_idx'), models.Index(fields=['txhash'], name='indexer_ton_txhash_6f3cfd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ton20Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=67)),
                ('tick', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=78, null=True)),
                ('txhash', models.CharField(max_length=67, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['wallet'], name='indexer_ton_wallet_a5e8e5_idx'), models.Index(fields=['tick'], name='indexer_ton_tick_4410e9_idx'), models.Index(fields=['amount'], name='indexer_ton_amount_a0c5ee_idx')],
                'unique_together': {('wallet', 'tick')},
            },
        ),
    ]
