# Generated by Django 5.0.2 on 2024-06-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0015_remove_transaction_fail_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ton20wallet',
            name='txhash',
            field=models.CharField(max_length=67),
        ),
    ]
