# Generated by Django 4.2.7 on 2024-06-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0017_alter_ton20wallet_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ton20tick',
            options={'ordering': ['tick']},
        ),
    ]
