# Generated by Django 4.2.7 on 2024-06-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0018_alter_ton20tick_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstatus',
            name='initiator',
            field=models.CharField(max_length=78, null=True),
        ),
        migrations.AddField(
            model_name='transactionstatus',
            name='mint_amount',
            field=models.DecimalField(decimal_places=0, max_digits=78, null=True),
        ),
        migrations.AddField(
            model_name='transactionstatus',
            name='op_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactionstatus',
            name='tick',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactionstatus',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=0, max_digits=78, null=True),
        ),
        migrations.AddField(
            model_name='transactionstatus',
            name='transfer_to',
            field=models.CharField(max_length=78, null=True),
        ),
        migrations.AlterField(
            model_name='ton20tick',
            name='deploy_by',
            field=models.CharField(max_length=78),
        ),
    ]
