# Generated by Django 4.2.7 on 2024-06-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0019_transactionstatus_initiator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstatus',
            name='memo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
