# Generated by Django 4.2.7 on 2024-06-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0020_transactionstatus_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstatus',
            name='in_msg_created_lt',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='transactionstatus',
            index=models.Index(fields=['in_msg_created_lt'], name='indexer_tra_in_msg__cfd0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionstatus',
            index=models.Index(fields=['transaction_hash'], name='indexer_tra_transac_6205ca_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionstatus',
            index=models.Index(fields=['success'], name='indexer_tra_success_d2aa10_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionstatus',
            index=models.Index(fields=['op_code'], name='indexer_tra_op_code_14a907_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionstatus',
            index=models.Index(fields=['tick'], name='indexer_tra_tick_b044f9_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionstatus',
            index=models.Index(fields=['initiator'], name='indexer_tra_initiat_11d64b_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionstatus',
            index=models.Index(fields=['transfer_to'], name='indexer_tra_transfe_0986a3_idx'),
        ),
    ]
